# Generated by Django 6.0.4 on 2026-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the lost/found item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item')),
                ('location', models.CharField(help_text='Location where the item was found', max_length=200)),
                ('date_found', models.DateField(help_text='Date when the item was found')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', help_text='Current status of the item', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the item was last updated')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
