# Generated by Django 6.0.4 on 2026-07-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_category_image_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_code',
        ),
    ]
