# Generated by Django 6.0.4 on 2026-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text='Internal note for administrators'),
        ),
        migrations.AddField(
            model_name='item',
            name='claimed_date',
            field=models.DateField(blank=True, help_text='Date when the item was claimed', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unid',
            field=models.CharField(blank=True, default='', help_text='UNID of the person who claimed the item', max_length=100),
        ),
    ]
