# Generated by Django 6.0.4 on 2026-04-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/title of the item', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the item')),
                ('image', models.ImageField(blank=True, help_text='Image of the item (optional)', null=True, upload_to='items/%Y/%m/%d/')),
                ('location', models.CharField(help_text='Location where the item was found or stored', max_length=200)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('claimed', 'Claimed'), ('returned', 'Returned'), ('expired', 'Expired')], default='stored', help_text='Current status of the item', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Date when the item expires and can be disposed of', null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="User's explanation of why they should get the item")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the claim', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the claim was created')),
                ('user', models.ForeignKey(help_text='The user making the claim', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The item being claimed', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-created_at'],
                'unique_together': {('item', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField(help_text='Scheduled pickup time')),
                ('checked_out', models.BooleanField(default=False, help_text='Whether the item has been picked up')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the reservation was created')),
                ('claim', models.OneToOneField(help_text='The approved claim for this reservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='items.claim')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['pickup_time'],
            },
        ),
    ]
